# Generated by Django 3.0.3 on 2020-02-08 21:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulletpointList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ein schöner Projektname.', max_length=30, verbose_name='Name')),
                ('date', models.DateField(verbose_name='Datum')),
                ('bulletpoint_lists', models.ManyToManyField(related_name='bulletpoint_lists', to='projects.BulletpointList')),
                ('paragraphs', models.ManyToManyField(related_name='paragraphs', to='projects.Paragraph')),
            ],
        ),
    ]
