# Generated by Django 3.0.3 on 2020-02-09 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='bulletpoint_lists',
        ),
        migrations.RemoveField(
            model_name='project',
            name='paragraphs',
        ),
        migrations.DeleteModel(
            name='BulletpointList',
        ),
        migrations.DeleteModel(
            name='Paragraph',
        ),
    ]
