# Generated by Django 3.0.3 on 2020-02-10 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Reihenfolge')),
                ('name', models.CharField(max_length=50, verbose_name='Bezeichnung')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Reihenfolge')),
                ('name', models.CharField(max_length=50, verbose_name='Bezeichnung')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.Project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Reihenfolge')),
                ('name', models.CharField(max_length=50, verbose_name='Bezeichnung')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Reihenfolge')),
                ('name', models.CharField(max_length=50, verbose_name='Bezeichnung')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.Paragraph')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titles', to='jobs.Job')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Reihenfolge')),
                ('index', models.IntegerField(verbose_name='Index')),
                ('name', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('unit', models.CharField(max_length=10, verbose_name='Einheit')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.Title')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='jobs.Job')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Reihenfolge')),
                ('name', models.CharField(max_length=50, verbose_name='Bezeichnung')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.Chapter')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='jobs.Job')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='paragraph',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.Section'),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paragraphs', to='jobs.Job'),
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Reihenfolge')),
                ('name', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, verbose_name='Menge')),
                ('unit', models.CharField(blank=True, max_length=10, null=True, verbose_name='Einheit')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineitems', to='jobs.Job')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.Task')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapters', to='jobs.Job'),
        ),
    ]
