# Generated by Django 3.0.3 on 2020-02-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Name',
            field=models.CharField(default='Name du Null', max_length=50, verbose_name='Bezeichnung'),
            preserve_default=False,
        ),
    ]
