# Generated by Django 3.0.3 on 2020-02-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=17, null=True, verbose_name='Menge'),
        ),
    ]
