# Generated by Django 3.0.3 on 2020-02-09 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Name',
            new_name='name',
        ),
    ]
